"""add assessment system tables

Revision ID: 93b895534639
Revises: c2aa040384a0
Create Date: 2026-08-29 10:32:11.616781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b895534639'
down_revision: Union[str, Sequence[str], None] = 'c2aa040384a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tpo_profile_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('topic', sa.String(length=150), nullable=False),
    sa.Column('subtopic', sa.String(length=150), nullable=True),
    sa.Column('question_type', sa.Enum('WRITTEN', 'CODING', 'SPOKEN', 'MCQ', name='question_type'), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty_level'), nullable=False),
    sa.Column('question_content', sa.JSON(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tpo_profile_id'], ['tpo_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('mode', sa.Enum('AUTOMATIC', 'MANUAL', 'ADAPTIVE', name='test_mode'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('creator_role', sa.Enum('TPO', 'DEPARTMENT', name='test_creator_role'), nullable=False),
    sa.Column('target_department_id', sa.UUID(), nullable=True),
    sa.Column('target_tpo_id', sa.UUID(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RELEASED', 'CLOSED', name='test_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_department_id'], ['department_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_tpo_id'], ['tpo_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('performance', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id')
    )
    op.create_table('test_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'SUBMITTED', 'MISSED', name='assignment_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('question_content', sa.JSON(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('question_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('question_bank_id', sa.UUID(), nullable=True),
    sa.Column('question_snapshot', sa.JSON(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['test_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_bank.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('obtained_marks', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('llm_report', sa.JSON(), nullable=True),
    sa.Column('llm_analysis_completed', sa.Boolean(), nullable=False),
    sa.Column('released', sa.Boolean(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['test_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    op.create_table('question_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_question_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_question_id'], ['assignment_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_responses')
    op.drop_table('test_results')
    op.drop_table('assignment_questions')
    op.drop_table('test_questions')
    op.drop_table('test_assignments')
    op.drop_table('student_performance')
    op.drop_table('tests')
    op.drop_table('question_bank')
    # ### end Alembic commands ###
